name: app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  ffi: ^2.1.4
  path_provider: ^2.1.5
  objectbox: ^5.0.3
  objectbox_flutter_libs: ^5.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.10.4
  objectbox_generator: ^5.0.3

flutter:

  uses-material-design: true

  assets:
    - assets/artifacts/
